project_id = "urcocghysdjfawmfitzj"

[functions.calculate-distance]
verify_jwt = false

[functions.places-autocomplete]
verify_jwt = false

[functions.generate-bouquet-preview]
verify_jwt = false

[functions.calculate-fedex-shipping]
verify_jwt = false

[functions.shopify-fedex-webhook]
verify_jwt = false

[functions.map-image]
verify_jwt = false

[functions.meta-capi]
verify_jwt = false

[functions.shopify-invoice-preview]
verify_jwt = false

[functions.shopify-invoice-print]
verify_jwt = false

[functions.fedex-key-check]
verify_jwt = false